### ISSUE TITLE
Confused by install guide. Have no `.mailfilter`

### ISSUE THREAD

**Issue by DerZyklop** [bhopmann/uberspace7-mailfilter#4]
The install guide tells me to rename my `.mailfilter` file. After "Installation of Bogofilter" i was inside /var/www/virtual/..myusername../bogofilter-1.2.5 – there was no `.mailfilter`. But in my home directory `~` there is also no `.mailfilter` file.  

https://github.com/bhopmann/uberspace7-mailfilter/blob/master/README.md#L35

**Comment by DerZyklop** [comment]
Is it possible that this is a relict from the U6 install guide? 🤔

**Comment by DerZyklop** [comment]
Probably related: step one under "Core Files" hints to U6 wiki. Seems odd since this install guide is made for U7.

https://github.com/bhopmann/uberspace7-mailfilter/blob/master/README.md#core-files

**Comment by bhopmann** [comment]
You'll have to use this file: https://github.com/bhopmann/uberspace7-mailfilter/blob/master/.mailfilter

**Comment by DerZyklop** [comment]
@bhopmann thank you, but do you think its correct, that uberspace7-mailfilter hints to the U6 mailfilter guide?

**Comment by DerZyklop** [comment]
Since the readme hints to U6 stuff, and i am not sure if this is intentionally i tried some setup myself based on this repo. I’m really not sure if i did it correctly, but it seems to work. Maybe this helps others that are confused by the readme. My thoughts and what i did:

U7 has its own mailfilter. The filter file is not called .mailfilter – it is called .spamfolder – so i added one line to the .mailfilter file from uberspace7-mailfilter:

```
# Here go the filter rules...
include "$HOME/.spamfolder" # <- i added this line
```

The setup described in uberspace7-mailfilter wants me to have one .mailfilter-EXT (where EXT is the name of the mail account like mail@my-domain.de needs .mailfilter-mail) per mail-account. But i don’t want to have multiple equal .mailfilter-EXT files. I added the .mailfilter file from the repo to ~ and besides that i created e.g. .mailfilter-mail and .mailfilter-hello both with this content:

```
include "$HOME/.mailfilter"
```

`~/bin/spam-learn` is running without problems. I’m not sure how to prove that incoming spam is sorted correctly.

**Comment by darkmattercoder** [comment]
Afaik that applies only if you use the system wide spam filter of U7, doesn't it?

**Comment by DerZyklop** [comment]
@darkmattercoder not sure what you mean with _»that«_. I would assume that some people who find this repo have the U7 spamfilter enabled. So i would recommend to mention in the README that either U7 spamfilter needs to be turned off, or how they work together. 

FYI: As soon as i figured out if my setup is working, i will change the README and create a pull request.

**Comment by bhopmann** [comment]
Since I'm not using the [spam filter of U7](https://manual.uberspace.de/mail-spam/), this script does not take this into account. But I would be very pleased, if you @DerZyklop could create a pull request with extending the README, which also works with the spam filter of U7.

> @bhopmann thank you, but do you think its correct, that uberspace7-mailfilter hints to the U6 mailfilter guide?

You're right. I made this decission, because the U7 manual lacks of hints according setting up `.qmail` and `maildrop`. But any other hints for setting this up are welcome, to avoid any confusing with U6/U7.

**Comment by bhopmann** [comment]
I've just removed the link to uberspace 6 wiki to avoid further confusion (see 66c9d674ec10c32c8771eb4c2b8de47277973526).

**Comment by DerZyklop** [comment]
Update: My Bogofilter is working great. Now i added some 

```
  SUBJECT = `reformail -x Subject:`
  xfilter "reformail -i\"Subject: $SUBJECT [TOOL X DID Y]\""
```

to my scripts to prove who did what. An example: I added 

```
  SUBJECT = `reformail -x Subject:`
  xfilter "reformail -i\"Subject: $SUBJECT [U7 marked this as SPAM]\""
```

somewhere in my `.spamfolder`. And 

```
  SUBJECT = `reformail -x Subject:`
  xfilter "reformail -i\"Subject: $SUBJECT [BOGOFILTER marked this as SPAM]\""
```

somewhere in my `.mailfilters/handlespam`.

As soon as i get my first U7 filtered SPAM mail besides Bogo filtered SPAM mails, i will create a pull request to extend your README. 

I see this ticket as closed.
